### ISSUE TITLE
Feedback for proposal

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/prepackR#6]
Great job with this proposal. The relationship to the R environment is well done and clear and I really like the tables of the parameters for each function. 

- Regarding splitter, there is a similar function in the package caret. I think its ok if you do a new implementation of this, but maybe check out what the caret function does, and what would you like it to do differently. 

- I would like to see more details on standardize features. From your description its not very clear what types of standardization will be done, and whether they will be done on all the columns. There is a similar version in the package vegan called decostand. Again, maybe check out this function.

- I would like to see for your three functions more description on what each of the parameters are. From the description it is not clear to me what 'methods' and 'methods_arg' are, what what are the differences between these two parameters. 

- Does NA counter work for every column of your data frame or only on a given column?

**Comment by smwatts** [comment]
**Comment 1**
To use Carat for data splitting, a user has to first separate a dataset into the x and y components. Carat will then return the indexes of the training/testing dataset. Our function will simplify this process by having the user pass in their entire dataset (the y component included) into our `splitter` function as well as the column that contains their target variable. Next, the `splitter` function will separate the y component from the dataset and split the data into a training/testing set. This function will return a single object (a list of data frames) that contain the x_train, y_train, x_test and y_test.

**Comment 2**
We will have 5 different types of standardization (this is different from the standardization package vegan called decostand). Our standardization is based on https://support.minitab.com/en-us/minitab/18/help-and-how-to/calculations-data-generation-and-matrices/standardize/standardize-columns-of-data/ (listed below)

1. Subtract mean and divide by standard deviation: Center the data and change the units to standard deviations. For a regression analysis, select this method to standardize predictors in order to reduce multicollinearity and to compare the size of the coefficients on a comparable scale.

2. Subtract mean: Center the data. For a regression analysis, select this method to standardize predictors in order to reduce multicollinearity. This method is helpful when your model contains highly correlated predictors, higher-order terms, and interaction terms.

3. Divide by standard deviation: Standardize the scale for each variable that you specify, so that you can compare them on a similar scale. For a regression analysis, select this method to standardize predictor variables in order to determine which predictors have a larger effect, while controlling for differences in scale.

4. Subtract first value, then divide by second: Enter your own values (such as known values for the mean and the standard deviation) to subtract from and divide by.

5. Make range from start to end: Transform the data linearly so that the resulting data have the first value that you specify as a minimum, and the second value that you specify as a maximum.

**Comment 3**
We have included more detailed documentation about our functions in the docstrings.

**Comment 4**
The NA counter will include a `columns` parameter that allows the user to indicate which columns they would like to look at. If this is empty then the NA values for all columns will be calculated
